#!/bin/bash

# get the filename from the user
read -p "Enter filename seperated by spaces " my_files

for filename in $my_files
do
echo $filename
echo -e "## $filename" >> README.md

# grab the last comment line with Return keyword
lastLineA=$(grep -i "^\* Return" $filename | xargs)
lastLineB=$(grep -i "^ \* Return" $filename | xargs)
echo "$lastLineA"
echo "$lastLineB"
# loop through file 
n=1
while read line; do
if [[ "$line" == \** ]]; then
    echo -e "$line" >> README.md
# else
#     echo "Match not found"
fi

if [ "$line" = "$lastLineA" ] || [ "$line" = "$lastLineB" ]
then
    echo "Yes"
    break
fi
n=$((n+1))

done < $filename
done
cat -n -E README.md
